### ISSUE TITLE
好像只有票星球是可以用的？

### ISSUE THREAD

**Issue by baichenshan370** [ThinkerWen/TicketMonitoring#10]
如题，是这样吗？

**Comment by ThinkerWen** [comment]
> 如题，是这样吗？

只有大麦不可用，其他3个都能用

**Comment by baichenshan370** [comment]
https://wx.maoyan.com/maoyansh/myshow/ajax/v2/performance/{self.performId}/shows/0
刚才试了下，猫眼的这个接口，杰伦的不行，但是周深的可以。。。

**Comment by ThinkerWen** [comment]
> [https://wx.maoyan.com/maoyansh/myshow/ajax/v2/performance/{self.performId}/shows/0](https://wx.maoyan.com/maoyansh/myshow/ajax/v2/performance/%7Bself.performId%7D/shows/0) 刚才试了下，猫眼的这个接口，杰伦的不行，但是周深的可以。。。

你测试的长沙的吧，长沙的还没开售

**Comment by baichenshan370** [comment]
长沙已经二开了。难道开售前这个接口就用不了了？

**Comment by ThinkerWen** [comment]
> 长沙已经二开了。难道开售前这个接口就用不了了？

现在场次是直接通过这个接口获取的，开售前这个接口不返回场次数据

**Comment by baichenshan370** [comment]
好吧
