### ISSUE TITLE
代码有错

### ISSUE THREAD

**Issue by sethSHJ** [ThinkerWen/TicketMonitoring#12]
不能返回有票的信息，只会不停重复监控中。票星球监控中写了个纷玩岛

**Comment by ThinkerWen** [comment]
> 不能返回有票的信息，只会不停重复监控中。票星球监控中写了个纷玩岛

问题描述清楚

**Comment by sethSHJ** [comment]
留个联系方式吧

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月03日 21:14 |
| 收件人 | ThinkerWen/TicketMonitoring ***@***.***> |
| 抄送人 | sethSHJ ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ThinkerWen/TicketMonitoring] 代码有错 (Issue #12) |

不能返回有票的信息，只会不停重复监控中。票星球监控中写了个纷玩岛

问题描述清楚

**Comment by sethSHJ** [comment]
> > 返回不能有票的信息，只能不停重复监控中。票星球监控中写了个纷玩岛
> 
> 问题描述清楚

不能返回有票的数据详情

**Comment by ThinkerWen** [comment]
> > > 返回不能有票的信息，只能不停重复监控中。票星球监控中写了个纷玩岛
> > 
> > 
> > 问题描述清楚
> 
> 不能返回有票的数据详情

哪个平台

**Comment by sethSHJ** [comment]
4个抢票平台的都不行啊，加你主页联系方式了，麻烦可以的话通过一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月06日 16:41 |
| 收件人 | ThinkerWen/TicketMonitoring ***@***.***> |
| 抄送人 | sethSHJ ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ThinkerWen/TicketMonitoring] 代码有错 (Issue #12) |

返回不能有票的信息，只能不停重复监控中。票星球监控中写了个纷玩岛

问题描述清楚

不能返回有票的数据详情

哪个平台
