### ISSUE TITLE
双击release的.exe文件闪退

### ISSUE THREAD

**Issue by whygong1** [ThinkerWen/TicketMonitoring#13]
双击release的.exe文件会闪退

**Comment by ThinkerWen** [comment]
> 双击release的.exe文件会闪退

在cmd命令行里面运行程序，看一下报错信息

**Comment by whygong1** [comment]
用cmd运行，也是弹一下窗口，就没了，啥也看不到

**Comment by ThinkerWen** [comment]
> 用cmd运行，也是弹一下窗口，就没了，啥也看不到

用**命令行**运行查看报错，而非直接打开程序

**Comment by Anitashixiziteng** [comment]
> 用cmd运行，也是弹一下窗口，就没了，啥也看不到

你解决了吗？我也都闪退

**Comment by dmfhyjk** [comment]
config里的时间早于现在时间，程序自动退出了
