### ISSUE TITLE
有票的演出，会报这个错，是什么原因呢？

### ISSUE THREAD

**Issue by qybgh** [ThinkerWen/TicketMonitoring#18]
![74d749685956cb5811b891e760012c7](https://github.com/user-attachments/assets/b7c999a1-4f79-4426-a9ce-2a3d4b4c87b6)

**Comment by ThinkerWen** [comment]
> ![74d749685956cb5811b891e760012c7](https://github.com/user-attachments/assets/b7c999a1-4f79-4426-a9ce-2a3d4b4c87b6)
> 
> 

大麦h5不能获取票的状态了

**Comment by BoringLiu** [comment]
所以现在大麦不能获取票务状态了吗？每次都会显示哎呦喂被挤爆了。。。期待大佬回复
