### ISSUE TITLE
哎哟喂,被挤爆啦,请稍后重试

### ISSUE THREAD

**Issue by haozhuoyi** [ThinkerWen/TicketMonitoring#2]
大佬我在执行大麦监控时出现了报错，是不是因为我的ip被大麦ban了：
![1698909778564](https://github.com/Raptor-wxw/TIcketMonitoring/assets/72720742/61e16f6a-8ea8-4428-b9e9-e4196b0ec813)
![1698909817866](https://github.com/Raptor-wxw/TIcketMonitoring/assets/72720742/824927dc-5916-4600-9d5f-0d72798011ab)

**Comment by ThinkerWen** [comment]
加上代理再请求试试呢？

**Comment by haozhuoyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by haozhuoyi** [comment]
哥们我有个想法，想搞个在线的web版的票监控平台，今天加了你微信，要不聊聊？
