### ISSUE TITLE
纷玩岛的show_id怎么获取？五月天上海的id是多少？

### ISSUE THREAD

**Issue by chengaomin** [ThinkerWen/TicketMonitoring#3]
纷玩岛的show_id怎么获取？五月天上海的id是多少？

**Comment by ThinkerWen** [comment]
抓包一下就可以了，具体可以看一下教程，网上很多的：
[https://juejin.cn/post/6844904182588112904](https://juejin.cn/post/6844904182588112904)

**Comment by wilson0312** [comment]
用花瓶在ios上抓好像是有防抓包的策略 我没抓到..只抓到了envelope接口
