### ISSUE TITLE
大麦还能用吗，只能app购买的场次不返回库存数据了

### ISSUE THREAD

**Issue by gxh27954** [ThinkerWen/TicketMonitoring#4]

**Comment by caicaiNa666** [comment]
大佬，这个python文件拉下来以后，怎么运行啊，现在没报错了，我本人是做前端开发的，这个python属实是有些吃力，一调试就自动退出，跑不起来  折腾一晚上了，数据库连接上了，好像就改了个数据库的 然后把python的解释器弄了一下  缺的依赖也安装上了  头疼！  望回复！！！
![微信截图_20231111004732](https://github.com/Raptor-wxw/TIcketMonitoring/assets/103826659/34dded56-d29a-4e9e-8800-9fe953338449)

**Comment by ThinkerWen** [comment]
刚看了下网页端接口确不能获取到了，该换种方式了

**Comment by xoyi** [comment]
确实，仅app购买的已经获取不到数据了好像

**Comment by xoyi** [comment]
好了，frida hook app的接口还可以用，不过一直得开着电脑模拟器比较麻烦

**Comment by lyc061115** [comment]
哥，能找你要个联系方式讨论一下吗

**Comment by rxl-tutu** [comment]
> 好了，frida hook app的接口还可以用，不过一直得开着电脑模拟器比较麻烦

你多久试的，现在好像不行了，关键的接口总是抓包不到，不知道是不是我操作方式有问题，方便的话希望得到您的指点
