### ISSUE TITLE
大佬 望回复！！！

### ISSUE THREAD

**Issue by caicaiNa666** [ThinkerWen/TicketMonitoring#5]
大佬，这个python文件拉下来以后，怎么运行啊，现在没报错了，我个人是做前端开发的，这个python其实是有些吃力，一调试就自动退出，跑不起来折腾了一晚上了，数据库连接上了，希望就改了个数据库的然后把python的解释器弄干了干涸的依赖也安装了头疼！望回复！！！
![微信截图_20231111004732](https://github.com/Raptor-wxw/TIcketMonitoring/assets/103826659/e55e4a88-94c5-4c21-af9e-9a8a7bf307d0)

**Comment by ThinkerWen** [comment]
你调试在哪里打的断点，这个截图没有日志，什么也看不出来。你可以在运行正常的地方打断点，单步走看到哪里退出的

**Comment by caicaiNa666** [comment]
大概知道什么原因了  是因为我数据库里面的字段没写内容导致的   属实是菜鸡一个
