### ISSUE TITLE
python start.py 有错误

### ISSUE THREAD

**Issue by John-zhan** [ThinkerWen/TicketMonitoring#6]
Traceback (most recent call last):
  File "/home/wang/code/github/tickets/ThinkerWen/TicketMonitoring/start.py", line 7, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

**Comment by ThinkerWen** [comment]
> Traceback (most recent call last): File "/home/wang/code/github/tickets/ThinkerWen/TicketMonitoring/start.py", line 7, in import pymysql ModuleNotFoundError: No module named 'pymysql'

重新拉代码

**Comment by ThinkerWen** [comment]
> Traceback (most recent call last): File "/home/wang/code/github/tickets/ThinkerWen/TicketMonitoring/start.py", line 7, in import pymysql ModuleNotFoundError: No module named 'pymysql'

重新拉代码
