### ISSUE TITLE
MonitorDM.py, line 79

### ISSUE THREAD

**Issue by alanwangcot** [ThinkerWen/TicketMonitoring#7]
这里应该是self.cookies

**Comment by ThinkerWen** [comment]
> 这里应该是self.cookies

这里的cookie会当做返回值return出去，所以不用self.cookies

**Comment by alanwangcot** [comment]
我fork出来的运行到这里会报错referenced before assignment，改为self.cookies后解决了

**Comment by alanwangcot** [comment]
不过大麦前两天改了要登录才能看场次信息，我这两天也在研究怎么解决，加你主页的微信了通过一下一起讨论讨论呗

**Comment by magang0425** [comment]
是需要改成 self.cookies 的，因为81行的时候用到了cookies，但是现在没有办法获取到库存信息了，performBases 现在返回的是空的
